apiVersion: v1
kind: Service
metadata:
  name: csat-service
  namespace: csat
  labels:
    app: csat
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: csat
